version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.2.0
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    network_mode: host

  web:
    build: web_app/.
    ports:
      - "80:8000"
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8000