version: "3.9"
services:
  grafana:
    build:
      context: grafana/.
    ports:
      - 9000:3000
    restart: always
    volumes:
      - /opt/grafana/logs:/var/log/grafana
      - /opt/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/provisioning:/home/grafana/conf/provisioning
      - /home/ubuntu/.aws/credentials:/usr/share/grafana/.aws/credentials
      
    user: '472' #grafana user id

  web_server:
    build:
      context: web_app/server/
    network_mode: host
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - ALLOW_CLIENT_URL=http://localhost:3005 
      # Server port 
      - PORT=9010
      # MYSQL DB credentials
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - GRAFANA_DB=grafana

  web_client:
    build:
      context: web_app/client/
    command: npm start
    restart: always
    depends_on:
      - web_server
    network_mode: host