version: "3.4"
services:
  rosbag2-processing-service:
    build:
          context: ./historical_data_processing
          dockerfile: Dockerfile
          network: host
    image: usdotfhwastoldev/rosbag2_processing_service:develop
    logging:
      options:
        max-size: "2g"
        max-file: "1"
    container_name: rosbag2_processing_service
    entrypoint: /ws/entrypoint.sh
    volumes:
           - ./logs:/var/logs
           - /home/carma/wfd_ws/test_rosbags:/home/carma/wfd_ws/test_rosbags
    environment:
    - TOPIC_EXCLUSION_LIST=["/rosout","/parameter_events","/robot_description","/tf_static","/tf","/environment/fused_external_objects","/environment/base_map","/environment/external_objects_viz","/environment/motion_computation_visualize","/environment/external_object_predictions","/localization/current_pose","/localization/map_param_loader/georeference","/environment/semantic_map","/hardware_interface/comms/outbound_binary_msg","/environment/lanelet2_map_viz","/localization/points_map"]
    - NATS_SERVER_IP_PORT=<>
    - LOG_LEVEL=debug
    - LOG_NAME=rosbag2_processing_service
    - LOG_PATH=/opt/telematics/logs
    - LOG_ROTATION_SIZE_BYTES=2147483648
    - LOG_HANDLER_TYPE=console
    - INFLUX_BUCKET=test-bucket
    - INFLUX_ORG=my-org
    - INFLUX_TOKEN=my-super-secret-auth-token
    - INFLUX_URL=<>
    - S3_MOUNTED_DIR=  #Leave empty for local deployment
    - TO_STR_FIELDS=[]
    - IGNORE_FIELDS=[]
    - NATS_REQUEST_TOPIC=ui.file.*
    - ACCEPTED_FILE_EXTENSIONS=[".mcap"]