name: "CI: Comprehensive Tests and Coverage Analysis"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, master, feature_gha_rosbag2_service]

env:
  TEST_RESULTS_PATH: test-results

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: carma_cloud_bridge_coverage
            docker_image: python:3.11
            test_path: telematic_system/telematic_units/carma_cloud_bridge/cloud_nats_bridge/test/
            requirements_file: telematic_system/telematic_units/carma_cloud_bridge/requirements.txt
            coverage_path: cloud_nats_bridge/test/coverage.xml

          - job_name: carma_vehicle_bridge_coverage
            docker_image: ros:foxy-ros1-bridge
            test_path: telematic_system/telematic_units/carma_vehicle_bridge/ros2_nats_bridge/test/
            requirements_file: ""
            coverage_path: ros2_nats_bridge/test/coverage.xml

          - job_name: telematic_cloud_messaging_coverage
            docker_image: openjdk:17-jdk-slim-buster
            test_path: telematic_system/telematic_cloud_messaging
            requirements_file: ""
            coverage_path: telematic_cloud_messaging/target

          - job_name: web_app_client_coverage
            docker_image: node:16.16.0
            test_path: telematic_system/telematic_apps/web_app/client
            requirements_file: ""
            coverage_path: web_app/client/coverage/*

          - job_name: web_app_server_coverage
            docker_image: node:16.16.0
            test_path: telematic_system/telematic_apps/web_app/server
            requirements_file: ""
            coverage_path: web_app/server/coverage/*

          - job_name: rosbag2_processing_service_coverage
            docker_image: ros:foxy
            test_path: telematic_system/historical_data_processing/rosbag2_processing_service/
            requirements_file: ""
            coverage_path: historical_data_processing/rosbag2_processing_service/coverage.xml

    container:
      image: ${{ matrix.docker_image }}
      options: --user root

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          apt-get update
          if [ -n "${{ matrix.requirements_file }}" ]; then
            apt-get -y install python3-coverage python3-pip python3-pytest
            python3 -m pip install -r $GITHUB_WORKSPACE/${{ matrix.requirements_file }}
          fi

      - name: Run Tests and Generate Coverage Report
        run: |
          if [ "${{ matrix.job_name }}" != "telematic_cloud_messaging_coverage" ]; then
            export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages
            cd $GITHUB_WORKSPACE/${{ matrix.test_path }}
            python3 -m coverage run -m pytest
            python3 -m coverage xml --omit="/opt/*,/root/*,/tmp/*,/usr/*,/var/*,**/__init__.py"
          fi

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.job_name }}-coverage
          path: $GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/${{ matrix.coverage_path }}
          if-no-files-found: error

  sonar-analysis:
    needs: setup-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v7

      - name: Download Code Coverage Results
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.TEST_RESULTS_PATH }}

      - name: Prepare SonarScanner properties
        run: |
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          echo "sonar.organization=your-organization" >> sonar-project.properties
          echo "sonar.projectKey=your-project-key" >> sonar-project.properties
          echo "sonar.projectName=your-project-name" >> sonar-project.properties
          echo "sonar.exclusions=**/__init__.py,**/*test*.py,**/test/**" >> sonar-project.properties
          echo "sonar.coverage.exclusions=**/__init__.py,**/*test*.py,**/test/**" >> sonar-project.properties
          echo "sonar.python.coverage.reportPaths=$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/carma_cloud_bridge_coverage/coverage.xml,$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/carma_vehicle_bridge_coverage/coverage.xml,$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/rosbag2_processing_service_coverage/coverage.xml" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/web_app_client_coverage/lcov.info,$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/web_app_server_coverage/lcov.info" >> sonar-project.properties
          echo "sonar.java.binaries=$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/telematic_cloud_messaging_coverage/target/classes" >> sonar-project.properties
          echo "sonar.coverage.jacoco.xmlReportPaths=$GITHUB_WORKSPACE/${{ env.TEST_RESULTS_PATH }}/telematic_cloud_messaging_coverage/target/site/jacoco/jacoco.xml" >> sonar-project.properties

      - name: Run SonarScanner
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
